# Site settings
title: Jiapeng’s Storybook
email: jiapeng.win@gmail.com
description: Jiapeng’s Blog | Tech&Thinking
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://jiapeng.win
permalink: /:year/:title


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  _neverm0re
weibo:    3130392561 # userID e.g. 3130392561
github:   kr0c
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: kr0c


# Google Analytics
google_analytics: UA-73003991-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
