# Site settings
title: Kr0c’s Storybook | Tech&Thinking
email: hi@kr0c.com
description: Kr0c’s Storybook | Tech&Thinking. This blog aims to take notes of my programming learning. Besides, it also shares book reviews and my true feelings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://kr0c.com
# permalink: /:year/:title.html


# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
twitter:  _neverm0re
weibo:    3130392561 # userID e.g. 3130392561
github:   kr0c
# codepen:  username
# dribbble: username


# Comment
disqus_shortname: kr0c


# Google Analytics
google_analytics: UA-73003991-1


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
